add_library(can
    src/at90can.c
    src/at90can_buffer.c
    src/at90can_disable_dyn_filter.c
    src/at90can_error_register.c
    src/at90can_get_buf_message.c
    src/at90can_get_dyn_filter.c
    src/at90can_get_message.c
    src/at90can_private.h
    src/at90can_send_buf_message.c
    src/at90can_send_message.c
    src/at90can_set_dyn_filter.c
    src/at90can_set_mode.c
    src/can_buffer.c
    src/mcp2515.c
    src/mcp2515_buffer.c
    src/mcp2515_defs.h
    src/mcp2515_error_register.c
    src/mcp2515_get_dyn_filter.c
    src/mcp2515_get_message.c
    src/mcp2515_private.h
    src/mcp2515_read_id.c
    src/mcp2515_regdump.c
    src/mcp2515_send_message.c
    src/mcp2515_set_dyn_filter.c
    src/mcp2515_set_mode.c
    src/mcp2515_sleep.c
    src/mcp2515_static_filter.c
    src/mcp2515_write_id.c
    src/sja1000.c
    src/sja1000_buffer.c
    src/sja1000_error_register.c
    src/sja1000_get_message.c
    src/sja1000_send_message.c
    src/sja1000_set_mode.c
    src/spi.c
)

target_include_directories(can
    PUBLIC
    ./include
)
